In [2]:
import csv

with open("winequality-red.csv", "r") as f:
    wines = list(csv.reader(f, delimiter = ";"))
print (wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [3]:
qualities = [float(item[-1]) for item in wines[1:]]

print sum(qualities)/len(qualities)

5.63602251407


In [4]:
import numpy as np

wines = np.array(wines[1:], dtype = np.float)
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [5]:
wines.shape

(1599L, 12L)

In [6]:
empty_array = np.zeros((3,4))
empty_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [7]:
np.random.rand(3,4)

array([[ 0.24197153,  0.37447232,  0.45973726,  0.5707848 ],
       [ 0.9649468 ,  0.18973255,  0.89645462,  0.89576651],
       [ 0.19584507,  0.14957945,  0.95224903,  0.14512672]])

In [8]:
wines = np.genfromtxt("winequality-red.csv", delimiter = ";", skip_header = 1)

In [9]:
wines[2,3]

2.2999999999999998

In [10]:
wines[0:3, 3]

array([ 1.9,  2.6,  2.3])

In [11]:
wines[3,:]

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,   9.8  ,   6.   ])

In [12]:
wines[:,:]

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [13]:
wines[1,5] = 10

In [14]:
wines[:,10] = 50

In [15]:
third_wines = wines[3, :]
third_wines

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,  50.   ,   6.   ])

In [16]:
third_wines[1]

0.28000000000000003

In [17]:
np.random.rand(3)

array([ 0.43206082,  0.74639971,  0.20790908])

In [18]:
year_one = [
    [500,505,490],
    [810,450,678],
    [234,897,430],
    [560,1023,640]
]

In [19]:
earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [20]:
earnings = np.array(earnings)
earnings[0,1,1]

450

In [21]:
earnings.shape

(2L, 4L, 3L)

In [22]:
earnings[:,0,:]

array([[500, 505, 490],
       [600, 605, 490]])

In [23]:
wines.dtype

dtype('float64')

In [24]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]])

In [25]:
int_wines = wines.astype(int)
int_wines.dtype.name

'int32'

In [26]:
np.int64

numpy.int64

In [27]:
wines.astype(np.int64)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]], dtype=int64)

In [28]:
wines[:,11] + 10

array([ 15.,  15.,  15., ...,  16.,  15.,  16.])

In [29]:
wines[:,11] += 10
wines[:,11]

array([ 15.,  15.,  15., ...,  16.,  15.,  16.])

In [30]:
wines[:,11] *2

array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [31]:
wines[:,10] * wines[:,10]

array([ 2500.,  2500.,  2500., ...,  2500.,  2500.,  2500.])

In [32]:
wines[:,11] + wines[:,11]

array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [33]:
array_one = np.array(
    [
[1,2],
[3,4]
    ]
)
array_two = np.array([4,5])
array_one + array_two

array([[5, 7],
       [7, 9]])

In [34]:
rand_array = np.random.rand(12)
wines + rand_array

array([[  8.33186584e+00,   9.02108497e-01,   2.88344974e-02, ...,
          8.03251035e-01,   5.03702212e+01,   1.51176974e+01],
       [  8.73186584e+00,   1.08210850e+00,   2.88344974e-02, ...,
          9.23251035e-01,   5.03702212e+01,   1.51176974e+01],
       [  8.73186584e+00,   9.62108497e-01,   6.88344974e-02, ...,
          8.93251035e-01,   5.03702212e+01,   1.51176974e+01],
       ..., 
       [  7.23186584e+00,   7.12108497e-01,   1.58834497e-01, ...,
          9.93251035e-01,   5.03702212e+01,   1.61176974e+01],
       [  6.83186584e+00,   8.47108497e-01,   1.48834497e-01, ...,
          9.53251035e-01,   5.03702212e+01,   1.51176974e+01],
       [  6.93186584e+00,   5.12108497e-01,   4.98834497e-01, ...,
          9.03251035e-01,   5.03702212e+01,   1.61176974e+01]])

In [35]:
wines[:,11].sum()

25002.0

In [36]:
wines.sum(axis = 0)

array([ 13303.1    ,    843.985  ,    433.29   ,   4059.55   ,
          139.859  ,  25369.     ,  74302.     ,   1593.79794,
         5294.47   ,   1052.38   ,  79950.     ,  25002.     ])

In [37]:
wines.sum(axis = 0).shape

(12L,)

In [38]:
wines.sum(axis = 1)

array([ 125.1438 ,  158.2548 ,  149.899  , ...,  149.48174,  155.01547,
        141.49249])

In [39]:
wines[:,11] > 5

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [40]:
wines[:,11] == 10

array([False, False, False, ..., False, False, False], dtype=bool)

In [41]:
high_quality = wines[:,11] > 7
wines[high_quality, :] [:3,:]

array([[  7.40000000e+00,   7.00000000e-01,   0.00000000e+00,
          1.90000000e+00,   7.60000000e-02,   1.10000000e+01,
          3.40000000e+01,   9.97800000e-01,   3.51000000e+00,
          5.60000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   8.80000000e-01,   0.00000000e+00,
          2.60000000e+00,   9.80000000e-02,   1.00000000e+01,
          6.70000000e+01,   9.96800000e-01,   3.20000000e+00,
          6.80000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   7.60000000e-01,   4.00000000e-02,
          2.30000000e+00,   9.20000000e-02,   1.50000000e+01,
          5.40000000e+01,   9.97000000e-01,   3.26000000e+00,
          6.50000000e-01,   5.00000000e+01,   1.50000000e+01]])

In [42]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol, 10:]

array([[ 50.,  15.],
       [ 50.,  15.],
       [ 50.,  15.],
       ..., 
       [ 50.,  16.],
       [ 50.,  15.],
       [ 50.,  16.]])

In [43]:
high_quality_and_wines = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol, 10:] = 20
wines[high_quality_and_alcohol,10:]

array([[ 20.,  20.],
       [ 20.,  20.],
       [ 20.,  20.],
       ..., 
       [ 20.,  20.],
       [ 20.,  20.],
       [ 20.,  20.]])

In [45]:
np.transpose(wines).shape

(12L, 1599L)

In [46]:
wines.ravel()

array([  7.4 ,   0.7 ,   0.  , ...,   0.66,  20.  ,  20.  ])

In [47]:
wines[1,:].reshape((2,6))

array([[  7.8   ,   0.88  ,   0.    ,   2.6   ,   0.098 ,  10.    ],
       [ 67.    ,   0.9968,   3.2   ,   0.68  ,  20.    ,  20.    ]])

In [49]:
white_wine = np.genfromtxt("winequality-white.csv", delimiter = ";", skip_header = 1)
white_wine.shape

(4898L, 12L)

In [52]:
all_wines = np.vstack((wines,white_wine))
all_wines.shape

(6497L, 12L)

In [54]:
np.concatenate((wines,white_wine),axis = 0)

array([[  7.4 ,   0.7 ,   0.  , ...,   0.56,  20.  ,  20.  ],
       [  7.8 ,   0.88,   0.  , ...,   0.68,  20.  ,  20.  ],
       [  7.8 ,   0.76,   0.04, ...,   0.65,  20.  ,  20.  ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   0.46,   9.4 ,   6.  ],
       [  5.5 ,   0.29,   0.3 , ...,   0.38,  12.8 ,   7.  ],
       [  6.  ,   0.21,   0.38, ...,   0.32,  11.8 ,   6.  ]])